FROM hysds/pge-base

ARG id
ARG gid

# copy job repo
COPY . /home/ops/verdi/ops/catify
RUN set -ex \
 && sudo chown -R ops:ops /home/ops/verdi/ops/catify

# set entrypoint
USER ops
WORKDIR /home/ops
CMD ["/bin/bash", "--login"]
